spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sophos-bank
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver